"""
Helper to create encrypted requests for any orchestration endpoint that uses authorization_security middleware.

Usage:
    # Test /process endpoint (default):
    python create_test_request.py
    
    # Test /feedback endpoint:
    python create_test_request.py feedback
    
    # Or use environment variable:
    TEST_MODE=feedback python create_test_request.py
    
Environment Variables:
    Process endpoint:
    - PROCESS_URL: URL of process endpoint (default: http://localhost:8000/api/v1/infiniti/signature-card)
    
    Feedback endpoint:
    - FEEDBACK_URL: URL of feedback endpoint (default: http://localhost:8000/api/v1/feedback)
    - REQ_ID: Request ID for feedback (default: abc123)
    - CASE_ID: Case ID for feedback (default: test_case_456)
    - REMARKS: Feedback remarks (default: Test feedback remarks...)
    - RESPONSE_FEEDBACK: Feedback value - "s" (satisfied) or "f" (feedback/issue) (default: s)
"""
import json
import os
import time
import hashlib
import base64
import urllib.request
import urllib.error
from cryptography.fernet import Fernet
from pathlib import Path

# Default test image (repo root: Insife a folder: "test_signature_cards" with a sample JPEG image named "test_image.jpg")
_DEFAULT_IMAGE = os.path.join(
    os.path.dirname(__file__), "..", "..", "test_signature_cards", "test_image.jpg"
)


def create_encrypted_request(
    client_id: str,
    api_key: str,
    encryption_key: str,
    image_path: str,
    metadata: dict = None,
    case_id: str = "test_case_456"
):
    """Build headers and body for an encrypted request. Returns dict with 'headers' and 'body'.
    
    Note: 
    - client_id is sent in headers (handled by auth middleware)
    - req_id is auto-generated by the server
    - parameters, mode, and detection_method are configured via environment variables
    """
    with open(image_path, 'rb') as f:
        file_data_b64 = base64.b64encode(f.read()).decode('utf-8')
    payload = {
        "file_data": file_data_b64,
        "case_id": case_id,
        "metadata": metadata or {}
    }
    cipher = Fernet(encryption_key.encode('utf-8'))
    encrypted_payload = cipher.encrypt(json.dumps(payload).encode('utf-8')).decode('utf-8')
    # Payload encryption done

    # hash : SHA256(api_key|client_id|timestamp|encrypted_payload)
    timestamp = str(int(time.time() * 1000))
    message = f"{api_key}|{client_id}|{timestamp}|{encrypted_payload}"
    hash_signature = hashlib.sha256(message.encode('utf-8')).hexdigest()
    return {
        "headers": {"client_id": client_id, "timestamp": timestamp, "hash": hash_signature, "Content-Type": "application/json"},
        "body": {"encrypted_payload": encrypted_payload}
    }


def create_encrypted_feedback_request(
    client_id: str,
    api_key: str,
    encryption_key: str,
    req_id: str,
    case_id: str,
    remarks: str = None,
    response_feedback: str = None
):
    """Build headers and body for an encrypted feedback request. Returns dict with 'headers' and 'body'.
    
    Note:
    - client_id is sent in headers (handled by auth middleware)
    - req_id, case_id, remarks, response_feedback are in the encrypted payload
    - response_feedback must be "s" (satisfied) or "f" (feedback/issue)
    """
    payload = {
        "req_id": req_id,
        "case_id": case_id,
    }
    if remarks is not None:
        payload["remarks"] = remarks
    if response_feedback is not None:
        payload["response_feedback"] = response_feedback
    
    cipher = Fernet(encryption_key.encode('utf-8'))
    encrypted_payload = cipher.encrypt(json.dumps(payload).encode('utf-8')).decode('utf-8')
    # Payload encryption done

    # hash : SHA256(api_key|client_id|timestamp|encrypted_payload)
    timestamp = str(int(time.time() * 1000))
    message = f"{api_key}|{client_id}|{timestamp}|{encrypted_payload}"
    hash_signature = hashlib.sha256(message.encode('utf-8')).hexdigest()
    return {
        "headers": {"client_id": client_id, "timestamp": timestamp, "hash": hash_signature, "Content-Type": "application/json"},
        "body": {"encrypted_payload": encrypted_payload}
    }


DEFAULT_PROCESS_URL = "http://localhost:8000/api/v1/infiniti/signature-card"
DEFAULT_FEEDBACK_URL = "http://localhost:8000/api/v1/feedback"

if __name__ == "__main__":
    import sys
    
    CLIENT_ID = "infy_5yh64"
    API_KEY = "c3effcdf-8c0c-47f9-96a8-84de81959c85"
    ENCRYPTION_KEY = "mWtlH2H4q84jPZJe4g17GFkLTNmlj1yWwiOd6jSovXM="
    
    # Check which test to run: process or feedback
    test_mode = os.getenv("TEST_MODE", "process")  # Default to process
    if len(sys.argv) > 1:
        test_mode = sys.argv[1].lower()
    
    if test_mode == "feedback":
        # Test feedback endpoint
        feedback_url = os.getenv("FEEDBACK_URL", DEFAULT_FEEDBACK_URL)
        req_id = os.getenv("REQ_ID", "voqnboio")  # Sample req_id
        case_id = os.getenv("CASE_ID", "test_case_456")
        remarks = os.getenv("REMARKS", "Test feedback remarks - extraction accuracy could be improved")
        response_feedback_env = os.getenv("RESPONSE_FEEDBACK", "s").lower()
        response_feedback = response_feedback_env if response_feedback_env in ("s", "f") else "s"
        
        print(f"Testing feedback endpoint: {feedback_url}")
        print(f"req_id: {req_id}, case_id: {case_id}")
        
        req = create_encrypted_feedback_request(
            CLIENT_ID, API_KEY, ENCRYPTION_KEY, req_id, case_id, remarks, response_feedback
        )
        
        body_json = json.dumps(req["body"])
        curl_cmd = (
            f'curl -X POST "{feedback_url}" '
            f'-H "client_id: {req["headers"]["client_id"]}" '
            f'-H "timestamp: {req["headers"]["timestamp"]}" '
            f'-H "hash: {req["headers"]["hash"]}" '
            f'-H "Content-Type: application/json" '
            f"-d '{body_json}'"
        )
        
        body_bytes = json.dumps(req["body"]).encode("utf-8")
        request = urllib.request.Request(
            feedback_url,
            data=body_bytes,
            headers=req["headers"],
            method="POST",
        )
        response_status = None
        response_body = ""
        try:
            with urllib.request.urlopen(request, timeout=30) as resp:
                data = resp.read().decode("utf-8")
                response_status = resp.status
                try:
                    out = json.loads(data)
                    response_body = json.dumps(out, indent=2)
                except json.JSONDecodeError:
                    response_body = data
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8")
            response_status = e.code
            try:
                err = json.loads(body)
                response_body = json.dumps(err, indent=2)
            except json.JSONDecodeError:
                response_body = body
        except urllib.error.URLError as e:
            response_status = "error"
            response_body = str(e.reason)
        
        out_path = os.path.join(os.path.dirname(__file__), "curl_and_response_feedback.txt")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("=== FEEDBACK TEST - CURL ===\n\n")
            f.write(curl_cmd)
            f.write("\n\n=== RESPONSE ===\n\n")
            f.write(f"Status: {response_status}\n\n")
            f.write(response_body)
            f.write("\n")
        
        print(f"Feedback test completed. Response saved to: {out_path}")
        print(f"Status: {response_status}")
        
        if response_status == "error":
            exit(1)
    
    else:
        # Test process endpoint (default)
        IMAGE_PATH = os.path.normpath(_DEFAULT_IMAGE)
        process_url = os.getenv("PROCESS_URL", DEFAULT_PROCESS_URL)
        
        if len(ENCRYPTION_KEY) != 44:
            print("Error: Invalid encryption key length")
            exit(1)
        if not Path(IMAGE_PATH).exists():
            print(f"Error: Image not found at {IMAGE_PATH}")
            exit(1)
        
        print(f"Testing process endpoint: {process_url}")
        print(f"Image: {IMAGE_PATH}")
        
        req = create_encrypted_request(CLIENT_ID, API_KEY, ENCRYPTION_KEY, IMAGE_PATH)

        body_json = json.dumps(req["body"])
        curl_cmd = (
            f'curl -X POST "{process_url}" '
            f'-H "client_id: {req["headers"]["client_id"]}" '
            f'-H "timestamp: {req["headers"]["timestamp"]}" '
            f'-H "hash: {req["headers"]["hash"]}" '
            f'-H "Content-Type: application/json" '
            f"-d '{body_json}'"
        )

        body_bytes = json.dumps(req["body"]).encode("utf-8")
        request = urllib.request.Request(
            process_url,
            data=body_bytes,
            headers=req["headers"],
            method="POST",
        )
        response_status = None
        response_body = ""
        try:
            with urllib.request.urlopen(request, timeout=300) as resp:
                data = resp.read().decode("utf-8")
                response_status = resp.status
                try:
                    out = json.loads(data)
                    response_body = json.dumps(out, indent=2)
                except json.JSONDecodeError:
                    response_body = data
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8")
            response_status = e.code
            try:
                err = json.loads(body)
                response_body = json.dumps(err, indent=2)
            except json.JSONDecodeError:
                response_body = body
        except urllib.error.URLError as e:
            response_status = "error"
            response_body = str(e.reason)

        out_path = os.path.join(os.path.dirname(__file__), "curl_and_response.txt")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("=== PROCESS TEST - CURL ===\n\n")
            f.write(curl_cmd)
            f.write("\n\n=== RESPONSE ===\n\n")
            f.write(f"Status: {response_status}\n\n")
            f.write(response_body)
            f.write("\n")

        print(f"Process test completed. Response saved to: {out_path}")
        print(f"Status: {response_status}")

        if response_status == "error":
            exit(1)
